version: '4'

services:
  SuperMarketApi:
    build: SuperMarketApi
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/SuperMarketDB
      DB_USER_NAME: root
      DB_PASSWORD: 12345678
    restart: always
    depends_on:
      - SuperMarketDB

  SuperMarketDB:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SuperMarketDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    restart: always
