spring.application.name=SuperMarketApi

## Server port
server.port=8095

spring.jpa.database=PostgreSQL
spring.jpa.show-sql=false
spring.session.jdbc.initialize-schema=always
# Hibernate DDL
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

## Configure Database
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}

spring.threads.virtual.enable = true
