spring.application.name=SuperMarketApi

## Server port
server.port=8095

spring.jpa.database=PostgreSQL
spring.jpa.show-sql=false
# Hibernate DDL
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

## Configure Database
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}

spring.threads.virtual.enable=true

## Spring Boot profile
spring.profiles.active=dev

# Environment file
spring.config.import=optional:file:.env[.properties]
