spring.application.name=SuperMarketApi

# Hibernate DDL
server.port=5090
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

## Configure Database
spring.jpa.database=PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.session.jdbc.initialize-schema=always
